# Rosé Pine Moon
[colors.primary]
background = "#232136"
foreground = "#e0def4"
bright_foreground = "#e0def4"
dim_foreground = "#6e6a86"

[colors.cursor]
cursor = "#e0def4"
text = "#232136"

[colors.normal]
black = "#2a273f"
red = "#eb6f92"
green = "#95b1ac"
yellow = "#f6c177"
blue = "#3e8fb0"
magenta = "#c4a7e7"
cyan = "#9ccfd8"
white = "#908caa"

[colors.bright]
black = "#393552"
red = "#eb6f92"
green = "#95b1ac"
yellow = "#f6c177"
blue = "#3e8fb0"
magenta = "#c4a7e7"
cyan = "#9ccfd8"
white = "#e0def4"

[window]
decorations = "none"
padding = { x = 3, y = 3 }
#opacity = 0.9

[window.dimensions]
columns = 180
lines = 50

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Retina Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 13.0
