-- Shared colorscheme builder for the owl themes.
-- Ported from mitsuhiko/agent-stuff (themes/nightowl.json, themes/dayowl.json).
-- Each colors/<name>.lua file gives a palette, and this module applies it.

local M = {}

--- Apply a palette as the current colorscheme.
--- @param name string colorscheme name
--- @param p table palette
function M.load(name, p)
  if vim.g.colors_name then
    vim.cmd 'highlight clear'
  end
  if vim.fn.exists 'syntax_on' == 1 then
    vim.cmd 'syntax reset'
  end
  vim.o.termguicolors = true
  vim.o.background = p.dark and 'dark' or 'light'
  vim.g.colors_name = name

  local hl = {
    -- editor
    Normal = { fg = p.fg, bg = p.bg },
    NormalNC = { fg = p.fg, bg = p.bg },
    NormalFloat = { fg = p.fg, bg = p.bg_float },
    FloatBorder = { fg = p.border, bg = p.bg_float },
    FloatTitle = { fg = p.accent, bg = p.bg_float, bold = true },
    ColorColumn = { bg = p.bg_alt },
    Conceal = { fg = p.fg_dark },
    Cursor = { fg = p.bg, bg = p.fg },
    lCursor = { fg = p.bg, bg = p.fg },
    CursorIM = { fg = p.bg, bg = p.fg },
    CursorLine = { bg = p.bg_highlight },
    CursorColumn = { bg = p.bg_highlight },
    CursorLineNr = { fg = p.accent, bold = true },
    LineNr = { fg = p.fg_dark },
    LineNrAbove = { fg = p.fg_dark },
    LineNrBelow = { fg = p.fg_dark },
    SignColumn = { bg = p.bg },
    FoldColumn = { fg = p.fg_dark, bg = p.bg },
    Folded = { fg = p.fg_dim, bg = p.bg_alt },
    VertSplit = { fg = p.border },
    WinSeparator = { fg = p.border },
    Directory = { fg = p.blue },
    EndOfBuffer = { fg = p.bg },
    NonText = { fg = p.fg_dark },
    Whitespace = { fg = p.bg_sel },
    SpecialKey = { fg = p.fg_dark },
    MatchParen = { fg = p.accent, bold = true },
    ModeMsg = { fg = p.fg, bold = true },
    MsgArea = { fg = p.fg },
    MoreMsg = { fg = p.blue },
    Question = { fg = p.blue },
    Title = { fg = p.blue, bold = true },
    Visual = { bg = p.bg_visual },
    VisualNOS = { bg = p.bg_visual },
    Search = { fg = p.bg, bg = p.yellow },
    IncSearch = { fg = p.bg, bg = p.orange },
    CurSearch = { fg = p.bg, bg = p.orange },
    Substitute = { fg = p.bg, bg = p.red },
    WarningMsg = { fg = p.yellow },
    ErrorMsg = { fg = p.red },
    Pmenu = { fg = p.fg, bg = p.bg_float },
    PmenuSel = { bg = p.bg_sel, bold = true },
    PmenuSbar = { bg = p.bg_alt },
    PmenuThumb = { bg = p.fg_dark },
    WildMenu = { bg = p.bg_sel },
    QuickFixLine = { bg = p.bg_sel, bold = true },
    StatusLine = { fg = p.fg, bg = p.bg_alt },
    StatusLineNC = { fg = p.fg_dark, bg = p.bg_alt },
    TabLine = { fg = p.fg_dim, bg = p.bg_alt },
    TabLineFill = { bg = p.bg_alt },
    TabLineSel = { fg = p.fg, bg = p.bg },
    WinBar = { fg = p.fg_dim, bg = p.bg },
    WinBarNC = { fg = p.fg_dark, bg = p.bg },

    -- diff
    DiffAdd = { bg = p.diff_add },
    DiffChange = { bg = p.diff_change },
    DiffDelete = { bg = p.diff_delete },
    DiffText = { bg = p.diff_text },
    diffAdded = { fg = p.green },
    diffRemoved = { fg = p.red },
    diffChanged = { fg = p.blue },
    diffFile = { fg = p.blue },
    diffLine = { fg = p.fg_dim },
    diffIndexLine = { fg = p.magenta },

    -- spell
    SpellBad = { sp = p.red, undercurl = true },
    SpellCap = { sp = p.yellow, undercurl = true },
    SpellLocal = { sp = p.cyan, undercurl = true },
    SpellRare = { sp = p.magenta, undercurl = true },

    -- syntax
    Comment = { fg = p.comment, italic = true },
    Constant = { fg = p.orange },
    String = { fg = p.string },
    Character = { fg = p.string },
    Number = { fg = p.number },
    Boolean = { fg = p.number },
    Float = { fg = p.number },
    Identifier = { fg = p.variable },
    Function = { fg = p.func },
    Statement = { fg = p.keyword },
    Conditional = { fg = p.keyword },
    Repeat = { fg = p.keyword },
    Label = { fg = p.keyword },
    Operator = { fg = p.operator },
    Keyword = { fg = p.keyword },
    Exception = { fg = p.keyword },
    PreProc = { fg = p.magenta },
    Include = { fg = p.keyword },
    Define = { fg = p.keyword },
    Macro = { fg = p.magenta },
    PreCondit = { fg = p.magenta },
    Type = { fg = p.type },
    StorageClass = { fg = p.keyword },
    Structure = { fg = p.type },
    Typedef = { fg = p.type },
    Special = { fg = p.cyan },
    SpecialChar = { fg = p.orange },
    Tag = { fg = p.blue },
    Delimiter = { fg = p.punct },
    SpecialComment = { fg = p.fg_dim, italic = true },
    Debug = { fg = p.red },
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Ignore = { fg = p.fg_dark },
    Error = { fg = p.red },
    Todo = { fg = p.bg, bg = p.yellow, bold = true },

    -- treesitter
    ['@comment'] = { link = 'Comment' },
    ['@comment.error'] = { fg = p.red },
    ['@comment.warning'] = { fg = p.yellow },
    ['@comment.todo'] = { link = 'Todo' },
    ['@comment.note'] = { fg = p.cyan },
    ['@constant'] = { fg = p.orange },
    ['@constant.builtin'] = { fg = p.orange },
    ['@constant.macro'] = { fg = p.magenta },
    ['@string'] = { fg = p.string },
    ['@string.escape'] = { fg = p.orange },
    ['@string.regexp'] = { fg = p.cyan },
    ['@string.special.url'] = { fg = p.cyan, underline = true },
    ['@character'] = { fg = p.string },
    ['@number'] = { fg = p.number },
    ['@boolean'] = { fg = p.number },
    ['@float'] = { fg = p.number },
    ['@function'] = { fg = p.func },
    ['@function.builtin'] = { fg = p.func },
    ['@function.macro'] = { fg = p.magenta },
    ['@function.method'] = { fg = p.func },
    ['@constructor'] = { fg = p.type },
    ['@parameter'] = { fg = p.variable },
    ['@variable'] = { fg = p.variable },
    ['@variable.builtin'] = { fg = p.red },
    ['@variable.parameter'] = { fg = p.variable },
    ['@variable.member'] = { fg = p.cyan },
    ['@property'] = { fg = p.cyan },
    ['@field'] = { fg = p.cyan },
    ['@keyword'] = { fg = p.keyword },
    ['@keyword.function'] = { fg = p.keyword },
    ['@keyword.operator'] = { fg = p.keyword },
    ['@keyword.return'] = { fg = p.keyword },
    ['@keyword.import'] = { fg = p.keyword },
    ['@operator'] = { fg = p.operator },
    ['@punctuation.delimiter'] = { fg = p.punct },
    ['@punctuation.bracket'] = { fg = p.punct },
    ['@punctuation.special'] = { fg = p.accent },
    ['@type'] = { fg = p.type },
    ['@type.builtin'] = { fg = p.type },
    ['@type.definition'] = { fg = p.type },
    ['@attribute'] = { fg = p.magenta },
    ['@label'] = { fg = p.keyword },
    ['@tag'] = { fg = p.keyword },
    ['@tag.attribute'] = { fg = p.cyan },
    ['@tag.delimiter'] = { fg = p.punct },
    ['@module'] = { fg = p.type },
    ['@namespace'] = { fg = p.type },
    ['@markup.heading'] = { fg = p.blue, bold = true },
    ['@markup.strong'] = { bold = true },
    ['@markup.italic'] = { italic = true },
    ['@markup.strikethrough'] = { strikethrough = true },
    ['@markup.underline'] = { underline = true },
    ['@markup.link'] = { fg = p.cyan },
    ['@markup.link.url'] = { fg = p.fg_dark, underline = true },
    ['@markup.raw'] = { fg = p.accent },
    ['@markup.list'] = { fg = p.accent },
    ['@markup.quote'] = { fg = p.fg_dim, italic = true },
    ['@diff.plus'] = { fg = p.green },
    ['@diff.minus'] = { fg = p.red },

    -- lsp
    LspReferenceText = { bg = p.bg_sel },
    LspReferenceRead = { bg = p.bg_sel },
    LspReferenceWrite = { bg = p.bg_sel },
    LspInlayHint = { fg = p.fg_dark, bg = p.bg_alt, italic = true },
    LspSignatureActiveParameter = { fg = p.accent, bold = true },
    LspCodeLens = { fg = p.fg_dark },
    ['@lsp.type.class'] = { link = '@type' },
    ['@lsp.type.decorator'] = { link = '@attribute' },
    ['@lsp.type.enum'] = { link = '@type' },
    ['@lsp.type.enumMember'] = { link = '@constant' },
    ['@lsp.type.interface'] = { link = '@type' },
    ['@lsp.type.function'] = { link = '@function' },
    ['@lsp.type.method'] = { link = '@function.method' },
    ['@lsp.type.namespace'] = { link = '@module' },
    ['@lsp.type.parameter'] = { link = '@variable.parameter' },
    ['@lsp.type.property'] = { link = '@property' },
    ['@lsp.type.struct'] = { link = '@type' },
    ['@lsp.type.type'] = { link = '@type' },
    ['@lsp.type.variable'] = { link = '@variable' },

    -- diagnostics
    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.yellow },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.cyan },
    DiagnosticOk = { fg = p.green },
    DiagnosticUnderlineError = { sp = p.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.cyan, undercurl = true },
    DiagnosticUnderlineOk = { sp = p.green, undercurl = true },
    DiagnosticVirtualTextError = { fg = p.red, bg = p.diff_delete },
    DiagnosticVirtualTextWarn = { fg = p.yellow, bg = p.diff_change },
    DiagnosticVirtualTextInfo = { fg = p.blue, bg = p.bg_alt },
    DiagnosticVirtualTextHint = { fg = p.cyan, bg = p.bg_alt },

    -- gitsigns
    GitSignsAdd = { fg = p.green },
    GitSignsChange = { fg = p.blue },
    GitSignsDelete = { fg = p.red },
    GitSignsAddInline = { bg = p.diff_add },
    GitSignsChangeInline = { bg = p.diff_change },
    GitSignsDeleteInline = { bg = p.diff_delete },

    -- telescope
    TelescopeNormal = { fg = p.fg, bg = p.bg_float },
    TelescopeBorder = { fg = p.border, bg = p.bg_float },
    TelescopeTitle = { fg = p.bg, bg = p.accent, bold = true },
    TelescopePromptNormal = { fg = p.fg, bg = p.bg_alt },
    TelescopePromptBorder = { fg = p.bg_alt, bg = p.bg_alt },
    TelescopePromptTitle = { fg = p.bg, bg = p.orange, bold = true },
    TelescopePromptPrefix = { fg = p.accent },
    TelescopeResultsTitle = { fg = p.bg_float, bg = p.bg_float },
    TelescopePreviewTitle = { fg = p.bg, bg = p.green, bold = true },
    TelescopeSelection = { bg = p.bg_sel, bold = true },
    TelescopeSelectionCaret = { fg = p.accent, bg = p.bg_sel },
    TelescopeMatching = { fg = p.accent, bold = true },

    -- nvim-cmp
    CmpItemAbbr = { fg = p.fg },
    CmpItemAbbrDeprecated = { fg = p.fg_dark, strikethrough = true },
    CmpItemAbbrMatch = { fg = p.accent, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = p.accent },
    CmpItemMenu = { fg = p.fg_dim },
    CmpItemKindDefault = { fg = p.fg_dim },
    CmpItemKindText = { fg = p.fg },
    CmpItemKindFunction = { fg = p.func },
    CmpItemKindMethod = { fg = p.func },
    CmpItemKindVariable = { fg = p.variable },
    CmpItemKindField = { fg = p.cyan },
    CmpItemKindProperty = { fg = p.cyan },
    CmpItemKindClass = { fg = p.type },
    CmpItemKindInterface = { fg = p.type },
    CmpItemKindStruct = { fg = p.type },
    CmpItemKindKeyword = { fg = p.keyword },
    CmpItemKindSnippet = { fg = p.green },
    CmpItemKindConstant = { fg = p.orange },
    CmpItemKindModule = { fg = p.type },
    CmpItemKindFile = { fg = p.blue },
    CmpItemKindFolder = { fg = p.blue },

    -- neo-tree
    NeoTreeNormal = { fg = p.fg, bg = p.bg_alt },
    NeoTreeNormalNC = { fg = p.fg, bg = p.bg_alt },
    NeoTreeWinSeparator = { fg = p.border, bg = p.bg_alt },
    NeoTreeEndOfBuffer = { fg = p.bg_alt, bg = p.bg_alt },
    NeoTreeRootName = { fg = p.accent, bold = true },
    NeoTreeDirectoryName = { fg = p.blue },
    NeoTreeDirectoryIcon = { fg = p.blue },
    NeoTreeFileName = { fg = p.fg },
    NeoTreeFileIcon = { fg = p.fg_dim },
    NeoTreeIndentMarker = { fg = p.bg_sel },
    NeoTreeCursorLine = { bg = p.bg_sel },
    NeoTreeGitAdded = { fg = p.green },
    NeoTreeGitModified = { fg = p.blue },
    NeoTreeGitDeleted = { fg = p.red },
    NeoTreeGitUntracked = { fg = p.fg_dim, italic = true },
    NeoTreeGitIgnored = { fg = p.fg_dark },
    NeoTreeGitConflict = { fg = p.orange },

    -- bufferline
    BufferLineFill = { bg = p.bg_alt },
    BufferLineBackground = { fg = p.fg_dark, bg = p.bg_alt },
    BufferLineBufferSelected = { fg = p.fg, bg = p.bg, bold = true },
    BufferLineBufferVisible = { fg = p.fg_dim, bg = p.bg_alt },
    BufferLineSeparator = { fg = p.bg_alt, bg = p.bg_alt },
    BufferLineSeparatorSelected = { fg = p.bg_alt, bg = p.bg },
    BufferLineIndicatorSelected = { fg = p.accent, bg = p.bg },
    BufferLineModified = { fg = p.green, bg = p.bg_alt },
    BufferLineModifiedSelected = { fg = p.green, bg = p.bg },

    -- misc plugins
    IndentBlanklineChar = { fg = p.bg_sel },
    IblIndent = { fg = p.bg_sel },
    IblScope = { fg = p.border },
    NotifyERRORBorder = { fg = p.red },
    NotifyWARNBorder = { fg = p.yellow },
    NotifyINFOBorder = { fg = p.blue },
    WhichKey = { fg = p.accent },
    WhichKeyGroup = { fg = p.blue },
    WhichKeyDesc = { fg = p.fg },
    WhichKeySeparator = { fg = p.fg_dark },
    WhichKeyFloat = { bg = p.bg_float },
  }

  for group, opts in pairs(hl) do
    vim.api.nvim_set_hl(0, group, opts)
  end

  -- terminal colors used by :terminal
  local t = p.terminal
  for i = 0, 15 do
    vim.g['terminal_color_' .. i] = t[i + 1]
  end
end

return M
